config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :simulations
  root 'welcome#index'

  resources :users

  get 'inicio'=>'welcome#index'

end

app/models/simulation.rb
class Simulation < ActiveRecord::Base
  belongs_to :user

  #validates :user_id, uniqueness: true, presence: true

  def user_name
    if self.user.blank?
      "-"
    else
      self.user.name
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :simulations

	#validates :name, presence: true
	validates :email, uniqueness: true, presence: true

	has_attached_file :avatar, style: { medium: "300x300", thumb: "100x100" }
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	def teste
		"teste teste"
	end

	def self.search(query)
		where("name like ?","%#{query}%")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/simulations_controller.rb
class SimulationsController < ApplicationController
  before_action :set_simulation, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [ :edit, :update, :new]
  before_action :authenticate_user!, except: [:index]

  def index
    @simulations = Simulation.all
  end

  def show
    @parametros = params
  end

  def new
    @simulation = Simulation.new
  end

  def edit
  end

  def create
    @simulation = Simulation.new(simulation_params)

    respond_to do |format|
      if @simulation.save
        format.html { redirect_to @simulation, notice: 'Simulation was successfully created.' }
        format.json { render :show, status: :created, location: @simulation }
      else
        format.html { render :new }
        format.json { render json: @simulation.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @simulation.update(simulation_params)
        format.html { redirect_to @simulation, notice: 'Simulation was successfully updated.' }
        format.json { render :show, status: :ok, location: @simulation }
      else
        format.html { render :edit }
        format.json { render json: @simulation.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @simulation.destroy
    respond_to do |format|
      format.html { redirect_to simulations_url, notice: 'Simulation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_simulation
      @simulation = Simulation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def simulation_params
      params.require(:simulation).permit(:name, :user_id)
    end

    def set_users
      @users = User.all
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @q = User.ransack(params[:q])
    @users = @q.result
    #if (params[:search])
    #  @users = User.search(params[:search])
    #else
    #  @users = User.all
    #end
    @instance = "Sou uma variável de instância"
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @parametros = params
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuário cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :birthday, :sex, :obs, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@variavel = "TExto"
		@partial = "partials"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simulad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/simulations/_form.html.erb
<%= form_for(@simulation) do |f| %>
  <% if @simulation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@simulation.errors.count, "error") %> prohibited this simulation from being saved:</h2>

      <ul>
      <% @simulation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%=  
        f.collection_select(:user_id, @users, :id, :name, {:include_blank=> true},{:class => 'form-control' })
      %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/simulations/edit.html.erb
<h1>Editing Simulation</h1>

<%= render 'form' %>

<%= link_to 'Show', @simulation %> |
<%= link_to 'Back', simulations_path %>

app/views/simulations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Simulations</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @simulations.each do |simulation| %>
      <tr>
        <td><%= simulation.name %></td>
        <td><%= simulation.user_name %></td>
        <td><%= link_to 'Show', simulation, :class => 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Edit', edit_simulation_path(simulation), :class => 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Destroy', simulation, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_simulation_path,
            :class => 'btn btn-primary' %>

app/views/simulations/new.html.erb
<h1>New Simulation</h1>

<%= render 'form' %>

<%= link_to 'Back', simulations_path %>

app/views/simulations/show.html.erb
<p id="notice"><%= notice %></p>
<%- model_class = Simulation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>


<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @simulation.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user) %>:</strong></dt>
  <dd><%= @simulation.user_name %></dd>
</dl>


<%= link_to 'Edit', edit_simulation_path(@simulation) %> |
<%= link_to 'Back', simulations_path %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal", multipart: true  } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :birthday, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :birthday, :class => 'form-control' %>
    </div>
    <%=f.error_span(:birthday) %>
  </div>
  <div class="form-group">
    <%= f.label :sex, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select(:sex,
        options_for_select([["Masculino", "M"], ["Feminino", "F"]], @user.sex),
        {include_blank: "Selecione"} , :class => 'form-control') %>
    </div>
    <%=f.error_span(:sex) %>
  </div>

  <div class="form-group">
    <%= f.label :obs, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :obs, :class => 'form-control' %>
    </div>
    <%=f.error_span(:obs) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.file_field :avatar %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>



<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<!-- formulário alterado para pesquisar com Ransack -->
<%= search_form_for @q do |f| %>
  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %>
  <%= f.submit %>
<% end %>


<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= sort_link(@q, :name) %></th>
      <th><%= sort_link(@q, :email) %></th>
      <th><%= model_class.human_attribute_name(:birthday) %></th>
      <th><%= model_class.human_attribute_name(:sex) %></th>
      <th><%= model_class.human_attribute_name(:obs) %></th>
      <th>
        Teste
      </th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.birthday %></td>
        <td><%= user.sex %></td>
        <td><%= user.obs %></td>
        <td>
          <%= user.teste %>
        </td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:birthday) %>:</strong></dt>
  <dd><%= @user.birthday %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sex) %>:</strong></dt>
  <dd><%= @user.sex %></dd>
  <dt><strong><%= model_class.human_attribute_name(:obs) %>:</strong></dt>
  <dd><%= @user.obs %></dd>
  <dt><strong>Image</strong></dt>
  <dd><%= image_tag @user.avatar.url %></dd>
</dl>
<dl>
  <% @user.simulations.each do |simulation| %>
    <dt><strong> User:</strong><%= simulation.name %></dt>

  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/welcome/_partial.html.erb
<%= "Oi, eu sou um #{@partial}." %>

app/views/welcome/index.html.erb
<h1>Teste de página Index na Welcome controller</h1>
<h2>Teste teste</h2>
<p><%= @variavel %></p>

<ul>
	<% if !user_signed_in? %>
	<li><%=	link_to 'Login', new_user_session_path %></li>
	<% else %>
	<li>Usuario atual: <%= current_user.email %> </li>
	<li>Session: <%= user_session %> </li>
	
	<li><%= link_to 'Usuários', users_path %></li>
	<li><%=	link_to 'Novo usuário', new_user_registration_path %></li>
	<li><%=	link_to 'Novo usuário (Antigo)', controller: :users, action: :new %></li>
	<li><%= link_to 'Simulações', simulations_path %></li>
	<li><%=	link_to 'Sair', destroy_user_session_path, method: :delete %></li>
	<% end %>
</ul>


<%= render 'partial' %>
<h3>I18n: <%= t('hello') %></h3>